# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Testing

on:
  push:
    branches-ignore: [master]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.4"]
    env:
      NOTIFY_SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      NOTIFY_SLACK_NOTIFY_CHANNEL: "oss-notices"
      NOTIFY_CURRENT_REPOSITORY_URL: "${{ github.server_url }}/${{ github.repository }}"
      NOTIFY_TEST_RUN_ID: "${{ github.run_id }}"
    permissions:
      contents: read
      id-token: write  # Required for OIDC authentication
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true
      - name: Update Bundle
        run: bundle check || bundle install
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Test
        run: bundle exec rake
      - name: Upload coverage to QLTY
        uses: qltysh/qlty-action/coverage@v1
        if: always()
        with:
          oidc: true
          files: coverage/coverage.json

  linter:
    name: Linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.4"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true
      - run: bundle exec standardrb
